Update api.py (#652)
* Update api.py

Sometimes the lims_is does not exist in lims. Then the sample will be created but sample.udf will give an error:

```
>>> s=Sample(lims, id='hoho')
>>> s.udf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mayabrandi/opt/genologics/genologics/descriptors.py", line 350, in __get__
    instance.get()
  File "/Users/mayabrandi/opt/genologics/genologics/entities.py", line 289, in get
    self.root = self.lims.get(self.uri)
  File "/Users/mayabrandi/opt/genologics/genologics/lims.py", line 90, in get
    return self.parse_response(r)
  File "/Users/mayabrandi/opt/genologics/genologics/lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "/Users/mayabrandi/opt/genologics/genologics/lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 404: Sample not found: hoho
```

* Fix code style issues with Black

* Update cg/apps/lims/api.py

Co-authored-by: Måns Magnusson <mans.magnusson@scilifelab.se>

* Update api.py

* Adds missing import and fix lint issues

* Fix code style issues with Black

* Fix type hint error

* Mock with mocker instead of mocking out api

* Instantiate before return

* Fix code style issues with Black

* Adds tests for get received date

* Adds tests for get dates in lims api

* Updates return types

* Fix code style issues with Black

* Adds deployment instructions

* Clearifies text

* Adds instructions for paxa

Co-authored-by: Lint Action <lint-action@samuelmeuli.com>
Co-authored-by: Måns Magnusson <mans.magnusson@scilifelab.se>